spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/cashback?serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  kafka:
    bootstrap-servers: kafka:29092
  data:
    redis:
      host: redis
      port: 6379