spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:mysql}:${DB_PORT:3306}/cashback?serverTimezone=Asia/Seoul
    username: ${DB_USERNAME:cashback_user}
    password: ${DB_PASSWORD:cashback1234}
  kafka:
    bootstrap-servers: kafka:29092
  data:
    redis:
      host: redis
      port: 6379